### ISSUE TITLE
Missing use statement in HttpApacheService.php

### ISSUE THREAD

**Issue by andkar73** [provision-ops/provision#3]
After the last commit to branch 4.x (Merge pull request #2 from provision4/4.x-step) I get the following error when i try to verify the apache server.

PHP Fatal error:  Uncaught Error: Class 'Aegir\Provision\Service\Http\Provision' not found in /var/www/provision/src/Provision/Service/Http/HttpApacheService.php:127
Stack trace:
#0 /var/www/provision/src/Provision/Service.php(97): Aegir\Provision\Service\Http\HttpApacheService->verifyServer()
#1 /var/www/provision/src/Provision/Context.php(631): Aegir\Provision\Service->verify()
#2 /var/www/provision/src/Provision/Command/VerifyCommand.php(83): Aegir\Provision\Context->verifyCommand()
#3 /var/www/provision/vendor/symfony/console/Command/Command.php(252): Aegir\Provision\Command\VerifyCommand->execute(Object(Aegir\Provision\Console\ArgvInput), Object(Aegir\Provision\Console\ConsoleOutput))
#4 /var/www/provision/vendor/symfony/console/Application.php(964): Symfony\Component\Console\Command\Command->run(Object(Aegir\Provision\Console\ArgvInput), Object(Aegir\Provision\Console\ConsoleOutput))
#5 /var/www/provision/src/Provision/Application.php(178): Symfony\Component\Console\Application->doRunCommand(Object(Aegir\Provision\Comman in /var/www/provision/src/Provision/Service/Http/HttpApacheService.php on line 127

The file src/Provision/Service/Http/HttpApacheService.php misses the use statement from Provision.
Add  "use Aegir\Provision\Provision;" to HttpApacheService.php fixes the problem.

**Comment by jonpugh** [comment]
Thank you!

I'm wondering how this passed the tests. Investigating now.

**Comment by jonpugh** [comment]
I see, the tests are using apacheDocker and the verifyServer() method doesn't invoke parent::verifyServer().

**Comment by jonpugh** [comment]
Hotfixing this for now. The entire verifyServer() method will change the next PR
